version: 2.1

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.9.9
    
    steps:
      - checkout
      - run:
          name: Install Python packages
          command: |
            pip install -e .[test,lint]
            sudo apt-get update -yqq
            sudo apt-get install jq -yqq

      - run:
          name: Lint Python
          command: black --check .

      - run:
          name: Run unit tests
          command: pytest --cov=dbt_cloud --cov-report html:cov_html

      - store_artifacts:
          path: ./cov_html

  integration-tests:
    docker:
      - image: cimg/python:3.9.9

    environment:
      DBT_CLOUD_PROJECT_ID: 26597
      DBT_CLOUD_ENVIRONMENT_ID: 49819
      DBT_CLOUD_JOB_ID: 43167

    steps:
      - checkout
      - run:
          name: Install Python packages
          command: |
            pip install -e .
            sudo apt-get update -yqq
            sudo apt-get install jq -yqq

      - run:
          name: Test 'dbt-cloud job get'
          command: |
            dbt-cloud job get --job-id $DBT_CLOUD_JOB_ID

      - run:
          name: Test 'dbt-cloud job list'
          command: |
            dbt-cloud job list | tee jobs.json
            job_count=$(cat jobs.json | jq '.data | length')
            [[ $job_count > 0 ]] && exit 0 || exit 1

      - run:
          name: Test 'dbt-cloud job export'
          command: |
            dbt-cloud job export | tee job.json

      - run:
          name: Test 'dbt-cloud job import'
          command: |
            cat job.json | dbt-cloud job import | tee job_imported.json

      - run:
          name: Test 'dbt-cloud job delete'
          command: |
            dbt-cloud job delete --job-id $(cat job_imported.json | jq .data.id)

      - run:
          name: Test 'dbt-cloud job delete-all'
          command: |
            dbt-cloud job delete-all --keep-jobs "[43167, 49663]" -y

workflows:
  version: 2
  continuous-integration:
    jobs:
      - unit-tests
      - approve:
          type: approval
      - integration-tests:
          requires:
            - approve