version: 2.1

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.9.9
    
    steps:
      - checkout
      - run:
          name: Install Python packages
          command: |
            pip install -e .[test,lint]
            sudo apt-get update -yqq
            sudo apt-get install jq -yqq

      - run:
          name: Lint Python
          command: black --check .

      - run:
          name: Run unit tests
          command: pytest --cov=dbt_cloud --cov-report html:cov_html

      - store_artifacts:
          path: ./cov_html

  integration-tests:
    docker:
      - image: cimg/python:3.9.9

    steps:
      - checkout

workflows:
  version: 2
  continuous-integration:
    jobs:
      - unit-tests
      - hold:
          type: approval
      - integration-tests:
          requires:
            - hold